apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vlan3-bond0
spec:
  desiredState:
    interfaces:
      - description: vlan3 using bond0
        ipv4:
          enabled: false
        name: bond0.3
        state: up
        type: vlan
        vlan:
          base-iface: bond0
          id: 3
      - bridge:
          allow-extra-patch-ports: true
          options:
            stp:
              enabled: false
          port:
            - name: bond0.3
        description: Bridge on VLAN4 using bond0
        ipv4:
          enabled: false
        name: br-3
        state: up
        type: ovs-bridge
    ovn:
      bridge-mappings:
        - bridge: br-3
          localnet: ovs-bridge-vlan3
          state: present