---
- name: Deploy ArgoCD Application
  kubernetes.core.k8s:
    state: present
    src: "{{ argocd_application }}"
  register: apply_result

- name: Waiting for ArgoCD Application creation
  ansible.builtin.pause:
    minutes: 1

- name: "Check if ArgoCD Application {{ app_name }} on namespace {{ argocd_namespace }} is Healthy"
  kubernetes.core.k8s_info:
    kind: Application
    api_version: "argoproj.io/v1alpha1"    
    namespace: "{{ argocd_namespace }}"
    name: "{{ app_name }}"
  register: app_health
  until: app_health.resources[0].status.health.status == 'Healthy'
  retries: 20
  delay: 30
  when: apply_result.changed

- name: "Wait for ArgoCD Application {{ app_name }} on namespace {{ argocd_namespace }} to be Synced"
  kubernetes.core.k8s_info:
    kind: Application
    api_version: "argoproj.io/v1alpha1"    
    namespace: "{{ argocd_namespace }}"
    name: "{{ app_name }}"
  register: app_ready
  until: app_ready.resources[0].status.sync.status == 'Synced'
  retries: 20
  delay: 30
  when: apply_result.changed