apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-apps-cert
  namespace: openshift-ingress
spec:
  secretName: wildcard-apps-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "gfontana.me"
  dnsNames:
  - "*.gfontana.me"
  - "*.simpsons.lab.gfontana.me"
  - "*.apps.simpsons.lab.gfontana.me"
  usages:
  - digital signature
  - key encipherment
  - server auth
  renewBefore: 720h  # Renew 30 days before expiry
