- op: add
  path: /spec/identityProviders/-
  value:
    name: github
    mappingMethod: claim
    type: GitHub
    github:
      clientID: Ov23lis1vDMZlwCtx7qw
      clientSecret:
        name: github-secret
      organizations:
        - gfontana-org
