apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  annotations:
    openshift.io/display-name: OpenShift Compliance Operator
  name: openshift-compliance
