---
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: registry
  name: argocd
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: quayregistry-role
  namespace: registry
rules:
  - verbs:
      - get
      - list
    apiGroups:
      - 'quay.redhat.com'
    resources:
      - quayregistries
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-view-quayregistry
  namespace: registry
subjects:
  - kind: ServiceAccount
    name: argocd
    namespace: registry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: quayregistry-role