---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: registry

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - namespace.yaml
  - init-config-bundle-secret.yaml
  - argocd-sa.yaml
  - set-init-user-passwd-job.yaml
  - quay-registry.yaml
