apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/compare-options: IgnoreExtraneous  

resources:
  - https://github.com/redhat-cop/gitops-catalog/loki-operator/operator/base