kind: Secret
apiVersion: v1
metadata:
  name: htpass-secret
  namespace: openshift-config
data:
  htpasswd: YWRtaW46JDJ5JDA1JHdrZnZjLmNublp5NGhJWmNTdDY0c2VsNlVBa2RvN3NaLjBJTFY5dkd1VVlZbElJUUJQTWgyCg==
type: Opaque
