---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-storage

commonAnnotations:
  argocd.argoproj.io/sync-wave: "0"

resources:
  - namespace.yaml
  - operator-group.yaml
  - subscription.yaml
  - enable-console-plugin.yaml
