apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clf-logging-loki.yaml
  - collect-app-logs-crb.yaml
  - collect-audit-logs-crb.yaml
  - collect-infra-logs-crb.yaml
  - collector-crb.yaml
  - collector-cr.yaml
  - collector-sa.yaml
  - loki-s3-secret-creation-job.yaml
  - lokistack.yaml
  - objectbucketclaim.yaml  