apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - operatorgroup.yaml
  - subscription.yaml
  - console-plugin-job.yaml

configMapGenerator:
  - name: job-console-plugin
    namespace: openshift-netobserv-operator
    behavior: merge
    files:
      - console-plugin-job.sh