apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: windows-efi-installer
  labels:
    app.kubernetes.io/version: v4.21.0
spec:
  description: >-
    This pipeline installs Windows 10/11/2k22/2k25 into a new DataVolume.
    Then the DataVolume is suitable to be used as a default boot source or
    golden image for Windows 10/11/2k22/2k25 VMs.
  params:
    - name: winImageDownloadURL
      description: Download URL to Windows installation ISO.
      type: string
    - name: acceptEula
      description: By setting this parameter, you are agreeing to the applicable Microsoft end user license agreement(s).
      type: string
    - name: autounattendXMLConfigMapsURL
      description: Download URL to ConfigMaps with Windows autounattend.xml file.
      type: string
      default: https://raw.githubusercontent.com/kubevirt/kubevirt-tekton-tasks/main/release/pipelines/windows-efi-installer/configmaps/windows-efi-installer-configmaps.yaml
    - name: instanceTypeName
      description: Name of VirtualMachineClusterInstancetype object
      type: string
      default: u1.large
    - name: instanceTypeKind
      description: Kind of VirtualMachineInstancetype object
      type: string
      default: VirtualMachineClusterInstancetype
    - name: preferenceName
      description: Name of VirtualMachineClusterPreference object
      type: string
      default: windows.11.virtio
    - name: virtualMachinePreferenceKind
      description: Kind of virtualMachinePreference object
      type: string
      default: VirtualMachineClusterPreference
    - name: autounattendConfigMapName
      description: Name of the ConfigMap containing the sysprep configuration files.
      type: string
      default: windows11-autounattend
    - name: virtioContainerDiskName
      description: Reference to the containerdisk containing the virtio-win drivers ISO.
      type: string
      default: registry.redhat.io/container-native-virtualization/virtio-win-rhel9:v4.21.0
    - name: baseDvName
      description: Name of the base DataVolume which is created.
      type: string
      default: win11
    - name: isoDVName
      description: Name of Windows ISO datavolume
      type: string
      default: win11
    - name: useBiosMode
      description: Set to true if the preference uses Bios instead of EFI.
      type: string
      default: "false"
  results:
    - name: baseDvName
      description: Name of the created base DataVolume
      value: $(tasks.create-vm-root-disk.results.name)
    - name: baseDvNamespace
      description: Namespace of the created base DataVolume
      value: $(tasks.create-vm-root-disk.results.namespace)
  tasks:
    - name: import-autounattend-configmaps
      params:
        - name: SCRIPT
          value: |
            if [ "$(params.acceptEula)" ]; then
              curl $(params.autounattendXMLConfigMapsURL) | \
              sed "s/<AcceptEula>false<\/AcceptEula>/<AcceptEula>true<\/AcceptEula>/g" | \
              oc apply -f -
            else
              echo "Microsoft Eula is not accepted"
              echo "Exiting"
              exit 1
            fi
        - name: VERSION
          value: latest
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: version
            value: "0.2.2"
        resolver: hub
    - name: import-win-iso
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              generateName: $(params.isoDVName)-
            spec:
              source:
                http:
                  url: $(params.winImageDownloadURL)
              storage:
                volumeMode: Filesystem
                resources:
                  requests:
                    storage: 9Gi
        - name: waitForSuccess
          value: "false"
        - name: allowReplace
          value: "true"
        - name: setOwnerReference
          value: "true"
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v4.21.0
        resolver: hub
    - name: create-vm-root-disk
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataVolume
            metadata:
              labels:
                "instancetype.kubevirt.io/default-instancetype-kind": $(params.instanceTypeKind)
                "instancetype.kubevirt.io/default-instancetype": $(params.instanceTypeName)
                "instancetype.kubevirt.io/default-preference-kind": $(params.virtualMachinePreferenceKind)
                "instancetype.kubevirt.io/default-preference": $(params.preferenceName)
              name: $(params.baseDvName)
            spec:
              storage:
                resources:
                  requests:
                    storage: 20Gi
              source:
                blank: {}
        - name: waitForSuccess
          value: "false"
        - name: allowReplace
          value: "true"
      runAfter:
        - import-autounattend-configmaps
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v4.21.0
        resolver: hub
    - name: modify-windows-iso-file
      params:
        - name: pvcName
          value: $(tasks.import-win-iso.results.name)
      runAfter:
        - import-win-iso
        - create-vm-root-disk
      when:
        - input: $(params.useBiosMode)
          operator: in
          values:
            - "false"
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-windows-iso-file
          - name: version
            value: v4.21.0
        resolver: hub
    - name: create-vm
      params:
        - name: runStrategy
          value: RerunOnFailure
        - name: setOwnerReference
          value: "true"
        - name: manifest
          value: |
            apiVersion: kubevirt.io/v1
            kind: VirtualMachine
            metadata:
              generateName: windows-efi-
            spec:
              instancetype:
                kind: $(params.instanceTypeKind)
                name: $(params.instanceTypeName)
              preference:
                kind: $(params.virtualMachinePreferenceKind)
                name: $(params.preferenceName)
              template:
                spec:
                  evictionStrategy: LiveMigrateIfPossible
                  domain:
                    devices:
                      disks:
                        - cdrom:
                            bus: sata
                          name: installcdrom
                          bootOrder: 2
                        - disk:
                            bus: virtio
                          name: rootdisk
                          bootOrder: 1
                        - cdrom:
                            bus: sata
                          name: virtiocontainerdisk
                        - cdrom:
                            bus: sata
                          name: sysprep
                  volumes:
                  - name: installcdrom
                    persistentVolumeClaim:
                      claimName: $(tasks.import-win-iso.results.name)
                  - name: virtiocontainerdisk
                    containerDisk:
                      image: $(params.virtioContainerDiskName)
                  - name: sysprep
                    sysprep:
                      configMap:
                        name: $(params.autounattendConfigMapName)
                  - dataVolume:
                      name: $(tasks.create-vm-root-disk.results.name)
                    name: rootdisk
      runAfter:
        - modify-windows-iso-file
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: create-vm-from-manifest
          - name: version
            value: v4.21.0
        resolver: hub
    - name: wait-for-vmi-status
      params:
        - name: vmiName
          value: $(tasks.create-vm.results.name)
        - name: vmiNamespace
          value: $(tasks.create-vm.results.namespace)
        - name: successCondition
          value: status.phase == Succeeded
        - name: failureCondition
          value: status.phase in (Failed, Unknown)
      runAfter:
        - create-vm
      timeout: 2h0m0s
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: wait-for-vmi-status
          - name: version
            value: v4.21.0
        resolver: hub
    - name: create-datasource-root-disk
      params:
        - name: manifest
          value: |
            apiVersion: cdi.kubevirt.io/v1beta1
            kind: DataSource
            metadata:
              labels:
                "instancetype.kubevirt.io/default-instancetype-kind": $(params.instanceTypeKind)
                "instancetype.kubevirt.io/default-instancetype": $(params.instanceTypeName)
                "instancetype.kubevirt.io/default-preference-kind": $(params.virtualMachinePreferenceKind)
                "instancetype.kubevirt.io/default-preference": $(params.preferenceName)
              name: $(tasks.create-vm-root-disk.results.name)
              namespace: $(tasks.create-vm-root-disk.results.namespace)
            spec:
              source:
                pvc:
                  name: $(tasks.create-vm-root-disk.results.name)
                  namespace: $(tasks.create-vm-root-disk.results.namespace)
        - name: waitForSuccess
          value: "false"
        - name: allowReplace
          value: "true"
      runAfter:
        - wait-for-vmi-status
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v4.21.0
        resolver: hub
  finally:
    - name: cleanup-vm
      params:
        - name: vmName
          value: $(tasks.create-vm.results.name)
        - name: vmNamespace
          value: $(tasks.create-vm.results.namespace)
        - name: delete
          value: "true"
      timeout: 10m0s
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: cleanup-vm
          - name: version
            value: v4.21.0
        resolver: hub
    - name: delete-imported-iso
      params:
        - name: deleteObject
          value: "true"
        - name: deleteObjectKind
          value: DataVolume
        - name: deleteObjectName
          value: $(tasks.import-win-iso.results.name)
        - name: namespace
          value: $(tasks.import-win-iso.results.namespace)
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: modify-data-object
          - name: version
            value: v4.21.0
        resolver: hub
    - name: delete-imported-configmaps
      params:
        - name: SCRIPT
          value: oc delete -f $(params.autounattendXMLConfigMapsURL)
        - name: VERSION
          value: latest
      taskRef:
        params:
          - name: catalog
            value: redhat-tekton-tasks
          - name: type
            value: artifact
          - name: kind
            value: task
          - name: name
            value: openshift-client
          - name: version
            value: "0.2.2"
        resolver: hub
