apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: pipelines-win-installer-scc
allowPrivilegedContainer: false
allowPrivilegeEscalation: true
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: false
requiredDropCapabilities:
  - MKNOD
runAsUser:
  type: RunAsAny
fsGroup:
  type: RunAsAny
seLinuxContext:
  type: MustRunAs
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - runtime/default
  - docker/default
  - localhost/*
volumes:
  - configMap
  - csi
  - downwardAPI
  - emptyDir
  - ephemeral
  - persistentVolumeClaim
  - projected
  - secret
users:
  - system:serviceaccount:vm-golden-images:pipeline
priority: 11
