apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgCUbVj1k2eAZ7jsuJP0LF9nEnOTWP9LzLx6CkKzsDGW9Je/i4+1gtV7/igThjrId4YLzzp7OyrYMHCK9eN8KMioM0Wbhmkb19SEUH6G+Sba4hRyFCvQcaw73h3Y4Biwe20YBfPPnfmCfO0cslsnXb3Hw/9XuiBLQV7tjb7My87mMR+tGWLZgagQKAN8z1zHF/OoPF6dSumlCyngOcxGupTZzJtKcjNCRohka6Sy4IIErWxm2pF3/Hr63C/uhDoqre8J1nmpl7Bqez5tv5JFunUUdGKwgveaVPC00ugGDn0DqdX5R6300Q/2VoH9/YhnQit8Rjis1B9HuqpUEYULv0jHKssSgfDV+80RTqaAGaWccK4Pjl8A7xcKu6aTZ/D4uUwmgpYaTyDb2JH8rxe/MLrIYG/FIXMFG0PPUwXJz5gUG3M0Gcken2AILVD5tN7GiWLbpBkTHj0qTe1XJ/7S9mJYwgLplNQ0dMWXkkWJYSl7mvdMjLShOZCc0tefqAiMNQQ7Xo6mKbyTjwZDm/k96ZElUeW1Q0LFMas/zeJV6B/kb+bB5xA4hirBYRXMrFiSGDKEKj0ihUfWh4DPbY+havry2MxKuoNPeLYyOuzNSIdBxDAesIlrW5UbX0b3Bext46MNz/KlZ5dWTLXwWfURP+2geTvwzrB4cqsjOxRxTqXqHldFzD6TqXYv0lZkwhpo1EzBl3jqVJEy5wX3xhO0/c+sY8zsvUtHx53Im12Tm8fgtJJDo2dMtU0M
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: openshift-config

