apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  labels:
    app: fedora-sample-vm
    vm.kubevirt.io/template: fedora-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.26.0
  name: fedora-sample-vm
  namespace: homelab-vms
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: fedora-sample-vm
      spec:
        source:
          registry:
            url: 'docker://quay.io/containerdisks/fedora:latest'
        storage:
          resources:
            requests:
              storage: 30Gi
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: fedora
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: fedora-sample-vm
        kubevirt.io/size: small
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              macAddress: '02:30:a3:00:00:02'
              model: virtio
              name: nic-arbitrary-albatross
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel9.2.0
        memory:
          guest: 16Gi
        resources: {}
      networks:
        - multus:
            networkName: tuning-bridge-fixed
          name: nic-arbitrary-albatross
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: fedora-sample-vm
          name: rootdisk
        - cloudInitConfigDrive:
            userData: |-
              #cloud-config
              user: fedora
              password: R3dh4t1!
              chpasswd: { expire: False }
          name: cloudinitdisk
