---
- name: Label Storage Nodes
  hosts: localhost
  become: false

  tasks:
    - name: Label Nodes
      kubernetes.core.k8s:
        kind: Node
        api_version: v1
        name: "{{ item }}"
        definition:
          metadata:
            labels:
              cluster.ocs.openshift.io/openshift-storage: ""
      loop: 
        - marge
        - bart
        - homer

- name: Deploy OpenShift Data Foundation
  hosts: localhost
  become: false

  roles:
    - role: argocd-app
      vars:
        argocd_application: "../../gitops/manifests/my-home-lab/argocd-apps/openshift-data-foundation/application.yaml" 
        app_name: openshift-data-foundation