---
- name: Label Storage Nodes
  hosts: localhost
  become: false

  tasks:
    - name: Label Nodes
      kubernetes.core.k8s:
        kind: Node
        api_version: v1
        name: "{{ item }}"
        definition:
          metadata:
            labels:
              cluster.ocs.openshift.io/openshift-storage: ""
      loop: 
        - marge
        - bart
        - homer

- name: Deploy OpenShift Data Foundation
  hosts: localhost
  become: false

  roles:
    - role: argocd-app
      vars:
        argocd_application: "../../gitops/manifests/my-home-lab/argocd-apps/openshift-data-foundation/application.yaml" 
        app_name: openshift-data-foundation
        num_retries: 40

- name: Wait for OpenShift Data Foundation to be fully deployed
  hosts: localhost
  become: false

  tasks:

    - name: "Wait for ocs-storagecluster to be Healthy"
      kubernetes.core.k8s_info:
        kind: StorageCluster
        api_version: "ocs.openshift.io/v1"
        namespace: openshift-storage
        name: ocs-storagecluster
      register: st_cluster_health
      until: (st_cluster_health.resources | length > 0) and (st_cluster_health.resources[0].status.phase == 'Healthy')
      retries: 120
      delay: 30
