apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgCSMp2L1M5zEHT8L5JS5mbFXI5zAdMSFNqghsiu9tZiXajRUsnyK7LsznCdRZPa+JE1X4RnBk7k+p2IYIx6MOk4lSVLnpiXt0OS8rcGf9xX6RO4LvPG+ViWjz7dy9jZzw9Gp6XmPYAli8PL6T6pzNjf+S0XUkqfnI+aCdLPrX+39ed7MLd/p5RzsHApYiYv4QdZwaL9J1zN4A/VTGJQEu58ItkhtrzOGuyskBRufnXPrTgmpNN8hFa7qqurZRToJxuULxozhY0Me3vSy9OsVprK3cbZFsf+Rl8DQ3MLx+FQIy5BcWdzRDQg+Sv8i/6q4LM7fOhUQ6RQSryGWNcliXeSoE2eZkyAyTkRP/X2DgKAqX9f2vCFZ9JNV3qSepdoFn0rVv8eX6iIWD+3SIz+Q1rw+5b95OVRzuonjguFOHeWtldUORlULRq5CB0e2OlOvJbbwl25K+MDm2qK8V7uhfWj5PTbAeqHyUWo73DQCD9E/fWjr67/l3ECM0BppmUJE4a2OPVqq50dXP9WlBE+69sdiJgMQD+WEIZoL6HVtd68rmffVT4VMnq6zUf16ljoPnehV2iKrOy7oUuEGxmK83XGYquLXcky29YXOWVLBoqjOVJgVq5bdgf/uSzFOP+gMPmsQgNTZnJEisnzHCcXuo7l4nXMzyYQYCahTX4VSDo5Poxfdi+gJMUDb9OYWkBxyKd8LcZSXE8SC3j3qrq7mx8b3Mnv+3XWB4z451pvnTX1v1gULB3yUGNz
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: openshift-config
    type: Opaque

