apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-pipeline
  namespace: demo-quarkus-pipeline
spec:
  finally:
    - name: clean-env
      params:
        - name: SCRIPT
          value: |-
            oc delete bc meat-helper

            oc delete is meat-helper

            rm -rf image-build
        - name: VERSION
          value: latest
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: meat-helper-cicd-pvc
  params:
    - name: GIT_URL
      type: string
    - name: GIT_BRANCH
      type: string
    - name: OUTPUT_IMAGE
      type: string
    - name: OUTPUT_TAG
      type: string
  tasks:
    - name: git-clone-code
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_BRANCH)
        - name: submodules
          value: 'true'
        - name: depth
          value: '10'
        - name: sslVerify
          value: 'true'
        - name: subdirectory
          value: src
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: meat-helper-cicd-pvc
    - name: build-app
      params:
        - name: MAVEN_IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/openshift/java:latest
        - name: GOALS
          value:
            - package
            - '-Dmaven.test.skip=true'
            - '-Dquarkus.container-image.push=false'
            - '-Dquarkus.container-image.build=false'
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SERVER_USER
          value: ''
        - name: SERVER_PASSWORD
          value: ''
        - name: PROXY_USER
          value: ''
        - name: PROXY_PASSWORD
          value: ''
        - name: PROXY_PORT
          value: ''
        - name: PROXY_HOST
          value: ''
        - name: PROXY_NON_PROXY_HOSTS
          value: ''
        - name: PROXY_PROTOCOL
          value: http
        - name: CONTEXT_DIR
          value: src
      runAfter:
        - git-clone-code
      taskRef:
        kind: ClusterTask
        name: maven
      workspaces:
        - name: source
          workspace: meat-helper-cicd-pvc
        - name: maven-settings
          workspace: maven-settings
    - name: push-build-artifact
      params:
        - name: SCRIPT
          value: >-
            echo "Pushing targets to artifact repository"

            echo "Push
            /workspace/manifest-dir/src/target/quarkus-meat-helper-1.0.0-SNAPSHOT.jar"

            echo "Target succesfully pushed"
        - name: VERSION
          value: latest
      runAfter:
        - build-app
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: meat-helper-cicd-pvc
    - name: build-image
      params:
        - name: SCRIPT
          value: >-
            oc new-build --strategy=docker --binary=true --context-dir=src
            --name meat-helper

            mkdir image-build && cp -R src/target image-build && cp
            src/src/main/docker/Dockerfile.jvm image-build/Dockerfile

            oc start-build meat-helper --from-dir=image-build --follow

            oc tag meat-helper:latest meat-helper:latest
            meat-helper:$(params.OUTPUT_TAG)
        - name: VERSION
          value: latest
      runAfter:
        - push-build-artifact
      taskRef:
        kind: ClusterTask
        name: openshift-client
      workspaces:
        - name: manifest-dir
          workspace: meat-helper-cicd-pvc
    - name: acs-image-scan
      params:
        - name: rox_api_token
          value: roxsecrets
        - name: rox_central_endpoint
          value: roxsecrets
        - name: output_format
          value: json
        - name: image
          value: >-
            image-registry.openshift-image-registry.svc:5000/demo-quarkus-pipeline/meat-helper:$(params.OUTPUT_TAG)
      runAfter:
        - build-image
      taskRef:
        kind: Task
        name: acs-image-scan
    - name: acs-image-check
      params:
        - name: image
          value: >-
            image-registry.openshift-image-registry.svc:5000/demo-quarkus-pipeline/meat-helper:$(params.OUTPUT_TAG)
        - name: rox_api_token
          value: roxsecrets
        - name: rox_central_endpoint
          value: roxsecrets
      runAfter:
        - acs-image-scan
      taskRef:
        kind: Task
        name: acs-image-check
    - name: push-image
      params:
        - name: srcImageURL
          value: >-
            docker://image-registry.openshift-image-registry.svc:5000/demo-quarkus-pipeline/meat-helper:$(params.OUTPUT_TAG)
        - name: destImageURL
          value: 'docker://quay-registry.apps.cluster-rht8s.rht8s.sandbox131.opentlc.com/meat-helper/demo:$(params.OUTPUT_TAG)'
        - name: srcTLSverify
          value: 'false'
        - name: destTLSverify
          value: 'false'
      runAfter:
        - acs-image-check
      taskRef:
        kind: ClusterTask
        name: skopeo-copy
      workspaces:
        - name: images-url
          workspace: meat-helper-cicd-pvc
  workspaces:
    - name: meat-helper-cicd-pvc
    - name: maven-settings
