apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: quarkus-pipeline-event-listener
  namespace: demo-quarkus-pipeline
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: quarkus-pipeline-binding
      template:
        ref: quarkus-pipeline-trigger-template
