---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: rhacs-operator

resources:
  - ../../base

patches:
  - path: patch-channel.yaml
    target:
      kind: Subscription
      name: rhacs-operator
