---
- hosts: all
  gather_facts: no
  collections:
    - dellemc.openmanage

  tasks:
    - name: "Power on BM nodes"
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        validate_certs: false
        reset_type: "On"

    - name: Pause for 2 minutes to power on servers
      ansible.builtin.pause:
        minutes: 2
