apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan1
  namespace: default
spec:
  config: '{
    "name":"vlan1",
    "type":"ovn-k8s-cni-overlay",
    "cniVersion":"0.4.0",
    "physicalNetworkName":"trunk",
    "vlanId": 1,
    "topology":"localnet",
    "netAttachDefName":"default/vlan1"
    }'