apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: localnet-vlan4
  namespace: default
spec:
  config: '{"name":"localnet-vlan4","type":"ovn-k8s-cni-overlay","cniVersion":"0.4.0","vlanId": 4,"topology":"localnet","netAttachDefName":"default/localnet-vlan4"}'