apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-ex-localnets
spec:
  desiredState:
    interfaces:
    ovn:
      bridge-mappings:
        - bridge: br-ex
          localnet: localnet-vlan4
          state: present