apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: trunk
spec:
  desiredState:
    ovn:
      bridge-mappings:
        - bridge: br-ex
          localnet: trunk
          state: present