---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stackrox

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

resources:
  - ../../base
  - stackrox-image-integration-update-job-sa.yaml
  - stackrox-image-puller-sa.yaml
  - stackrox-image-puller-token-secret.yaml
  - stackrox-image-integration-update-job.yaml
