apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeSet
metadata:
  name: hardware-localvolumeset
  namespace: openshift-local-storage
spec:
  deviceInclusionSpec:
    deviceMechanicalProperties:
      - Rotational
      - NonRotational
    deviceTypes:
      - disk
      - part
    minSize: 10G
  nodeSelector:
    nodeSelectorTerms:
      - matchExpressions:
          - values:
              - marge
              - bart
              - homer
            key: kubernetes.io/hostname
            operator: In
  maxDeviceCount: 10
  storageClassName: local-sc
  volumeMode: Block
