apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configure-auth
  namespace: argocd-flanders
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
spec:
  destination:
    namespace: argocd-manager
    server: https://api.flanders.lab.gfontana.me:6443
  project: default
  source:
    path: gitops/manifests/clusters/all/aggregate/auth/
    repoURL: https://github.com/giofontana/gitops-ocp-infra.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
