apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configure-auth.yaml
  - cert-manager.yaml
  - cert-manager-certs.yaml
  - network.yaml
  - openshift-virtualization.yaml
