kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meat-helper-cicd-pvc
  namespace: demo-quarkus-pipeline
  annotations:
    argocd.argoproj.io/sync-options: { "health": false }
    argocd.argoproj.io/automated: "false"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
