---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: openshift-compliance

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  argocd.argoproj.io/sync-wave: "5"

resources:
  - ../../operator/overlays/release-0.1
  - demo-scan-setting-binding.yaml
