---
- hosts: localhost
  gather_facts: no
  collections:
    - dellemc.openmanage

  tasks:
    - name: "Performing graceful shutdown operation"
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ hostvars[item]['ansible_host'] }}"
        username: "{{ hostvars[item]['ansible_user'] }}"
        password: "{{ hostvars[item]['ansible_password'] }}"
        validate_certs: false
        reset_type: "GracefulShutdown"
      loop: "{{ groups['all'] }}"        

    - name: "Wait 15 mins and force shutdown servers"
      pause:
        minutes: 15

    - name: "Performing force shutdown operation"
      dellemc.openmanage.redfish_powerstate:
        baseuri: "{{ hostvars[item]['ansible_host'] }}"
        username: "{{ hostvars[item]['ansible_user'] }}"
        password: "{{ hostvars[item]['ansible_password'] }}"
        validate_certs: false
        reset_type: "ForceOff"
      loop: "{{ groups['all'] }}"        
