apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-secret
  namespace: openshift-config
spec:
  encryptedData:
    clientSecret: AgB+zib1rcN68Ah7ShKYkDoXM+TP8xOYgCALmQmHiNRvhHKMia3l8/G+JJGyyR7o0ONjzuaccqBmgQm2Yn5M1KwP7uhkyiZphXIHqmaT/P+fWYhsMojz35wUK6nizAuQHV1U31Q0YIfdLoxfuSdjsk4GgStshDs0dJAoFVFhx5EuLeczqJwnJK9XBbw1ycGGec4per6SwzPv0HNe6KbHwFuaNypc7XD9GPfFCNwYi/9Ra5CCpnFFhyL6+kpArrdYYIJ9Uh56DtcRZwtKmeZWDvUjSADF16bfNdOI/FYoXesvYbeTssB/Pg5bffHe+YCB+q9Yu0+r7N0wHRriEMa0Ya8BLuQRj7kugrsWFAk+wQFWzhnWoc38IwBb/H7QaCXOg9ZKYMIRsirxYIERVeCubm5nxbC297zCtnNhGpzZrOOAPF23llxMyN1syMLl983ZFBvNCGzWs2P//3dZ6HyDNOdZZbFKFgDbEMUfdMTvxoadLE35CzyXTEeQk3F7YNGbSTgGDEYl/wwf6Rx2bpuvoO5cJid7jL1hmBs9muzLc6WAc9rmy97+PzXVjIMYnd1q3G7nsW07zJSHXMoMdnlvapeT3B6as05f7P5oFd0HC7p1xTBk58RcpYzolR677So3yjyyprso9ThH7m4HtBf8v4Clh2ViLLi+80noyM0nXahmqtWH+MKNELx45TpmOJefks1QFztA/isPB9DSGixEVROM/lplsMB9jUzyIcVaAKTABayg/GVbqZJ5
  template:
    metadata:
      creationTimestamp: null
      name: github-secret
      namespace: openshift-config
    type: Opaque

