apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-custom-disk-rotational-master
  labels:
    machineconfiguration.openshift.io/role: master  
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:text/plain;charset=utf-8;base64,QUNUSU9OPT0iYWRkfGNoYW5nZSIsIEtFUk5FTD09InNkW2Etel18c2NpbmkqfG52bWVbMC05XSoiLCBTVUJTWVNURU09PSJibG9jayIsICBBVFRSe3F1ZXVlL3JvdGF0aW9uYWx9PSIwIgo=
          mode: 420
          overwrite: true
          path: /etc/udev/rules.d/99-disable-rotational.rules
