#######
# 
# Workaround for ODF to work with HDD disks. Only works with:
#  Node name: marge.simpsons.lab.gfontana.me - DISK_WWN="wwn-0x644a84202ca9cf002f5c702849484052
#  Node name: bart.simpsons.lab.gfontana.me - DISK_WWN="wwn-0x61866da063b4c9002e9c3f2023019681
#  Node name: homer.simpsons.lab.gfontana.me - DISK_WWN="wwn-0x61866da062ba8a002e9c435a0f77c154
#
######
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 99-custom-disk-rotational
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: 'data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCiMgR2V0IHRoZSBob3N0bmFtZSBvZiB0aGUgbWFjaGluZQpIT1NUTkFNRT0kKGhvc3RuYW1lKQoKIyBEZWZpbmUgdGhlIGRpc2sgV1dOIGJhc2VkIG9uIHRoZSBob3N0bmFtZQpjYXNlICIkSE9TVE5BTUUiIGluCiAgICAibWFyZ2Uuc2ltcHNvbnMubGFiLmdmb250YW5hLm1lIikKICAgICAgICBESVNLX1dXTj0id3duLTB4NjQ0YTg0MjAyY2E5Y2YwMDJmNWM3MDI4NDk0ODQwNTIiCiAgICAgICAgOzsKICAgICJiYXJ0LnNpbXBzb25zLmxhYi5nZm9udGFuYS5tZSIpCiAgICAgICAgRElTS19XV049Ind3bi0weDYxODY2ZGEwNjNiNGM5MDAyZTljM2YyMDIzMDE5NjgxIgogICAgICAgIDs7CiAgICAiaG9tZXIuc2ltcHNvbnMubGFiLmdmb250YW5hLm1lIikKICAgICAgICBESVNLX1dXTj0id3duLTB4NjE4NjZkYTA2MmJhOGEwMDJlOWM0MzVhMGY3N2MxNTQiCiAgICAgICAgOzsKICAgICopCiAgICAgICAgZWNobyAiSG9zdG5hbWUgbm90IHJlY29nbml6ZWQuIEV4aXRpbmcuIgogICAgICAgIGV4aXQgMQogICAgICAgIDs7CmVzYWMKCiMgRmluZCB0aGUgY29ycmVzcG9uZGluZyBkaXNrIGRldmljZQpESVNLX0lEPSQocmVhZGxpbmsgLWYgIi9kZXYvZGlzay9ieS1pZC8kRElTS19XV04iIHwgYXdrIC1GJy8nICd7cHJpbnQgJE5GfScpCgppZiBbIC1uICIkRElTS19JRCIgXTsgdGhlbgogICAgZWNobyAiU2V0dGluZyByb3RhdGlvbmFsIHZhbHVlIHRvIDAgZm9yICRESVNLX0lEIgogICAgc3VkbyBiYXNoIC1jICJlY2hvIDAgPiAvc3lzL2Jsb2NrLyR7RElTS19JRH0vcXVldWUvcm90YXRpb25hbCIKZWxzZQogICAgZWNobyAiRGlzayBub3QgZm91bmQgZm9yIFdXTjogJERJU0tfV1dOIgogICAgZXhpdCAxCmZpCgo='
          mode: 493
          overwrite: true
          path: /usr/local/bin/set-disk-rotational.sh
    systemd:
      units:
        - contents: |
            [Unit]
            Description=Set Disk Rotational Attribute
            After=network-online.target
            Wants=network-online.target

            [Service]
            Type=oneshot
            ExecStart=/usr/local/bin/set-disk-rotational.sh
            RemainAfterExit=true

            [Install]
            WantedBy=multi-user.target
          enabled: true
          name: set-disk-rotational.service
